# ---------------------------------------------------------------
# Theme Core Configuration Settings
# See: https://yaoqs.github.io/hexo-theme-scholar-future
# ---------------------------------------------------------------

#https://hexo.io/zh-cn/docs/themes
#主题的配置文件。和 Hexo 配置文件不同，主题配置文件修改时会自动更新，无需重启 Hexo Server。
#https://hexo.io/zh-cn/docs/configuration#%E4%BD%BF%E7%94%A8%E4%BB%A3%E6%9B%BF%E4%B8%BB%E9%A2%98%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
#我们强烈建议你将所有的主题配置集中在一处。如果你不得不在多处配置你的主题，那么这些信息对你将会非常有用：Hexo 在合并主题配置时，Hexo 配置文件中的 theme_config 的优先级最高，其次是 _config.[theme].yml 文件，最后是位于主题目录下的 _config.yml 文件。
name: scholar-future
description: A scholar magazine/journal like blog，FUTURE & CIVILIZATION，Natural/Social Philosophy & Infomation Sciences
keywords: FUTURE & CIVILIZATION，Natural/Social Philosophy & Infomation Sciences
logo: /images/githubavatar.png
slogan:
  sub1: 解放思想，发展生产力
  sub2: 为天地立心，<br>为生民立命，<br>为往圣继绝学，<br>为万世开太平。
  sub3: 知行合一
  sub4: 凡事预则立，不预则废
  sub5: 茍日新，日日新，又日新
  sub6: 天之道，利而不害；<br>圣人之道，为而不争
Email: 350788415@qq.com
Author: Yao Qing-sheng
githubname: yaoqs
Address: Department of Natural/Social Philosophy & Infomation Sciences, CHINA
Repositories_Pages: https://yaoqs.github.io/
rss: /atom.xml
disqus:
custom_html_list: [About,Lab,Navigator,Feature,Doante,Game,Music]


Site_visit_tongji:
  google_analytics:
  baidu: <script type="text/javascript">var _hmt = _hmt || [];(function() {  var hm = document.createElement("script");  hm.src = "https://hm.baidu.com/hm.js?2023f967cb85513ede1b6a3d58177776";  var s = document.getElementsByTagName("script")[0];   s.parentNode.insertBefore(hm, s);})();</script>
  cnzz: <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" :"http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1278269244'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1278269244%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
  umengplus: <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" :"http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1278269244'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1278269244%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
  qq_ta: <script type="text/javascript" src="https://tajs.qq.com/stats?sId=66496804" charset="UTF-8" async></script>
  flagcounter: <a href="https://info.flagcounter.com/tQfY"><img src="https://s11.flagcounter.com/mini/tQfY/bg_FFFFFF/txt_000000/border_CCCCCC/flags_0/" alt="Flag Counter" border="0"></a>
  _360fenxi: <script>(function(b,a,e,h,f,c,g,s){b[h]=b[h]||function(){(b[h].c=b[h].c||[]).push(arguments)};b[h].s=!!c;g=a.getElementsByTagName(e)[0];s=a.createElement(e);s.src="//s.union.360.cn/"+f+".js";s.defer=!0;s.async=!0;g.parentNode.insertBefore(s,g)})(window,document,"script","_qha",332983,false);</script>
  _51la_v5: <script type="text/javascript" src="//js.users.51.la/21341261.js"></script>
  _51la_v6: <script charset="UTF-8" id="LA_COLLECT" src="//sdk.51.la/js-sdk-pro.min.js?id=JhwXbvPO5Ijy6W6x&ck=JhwXbvPO5Ijy6W6x"></script><script id="LA-DATA-WIDGET" crossorigin="anonymous" charset="UTF-8" src="https://v6-widget.51.la/v6/JhwXbvPO5Ijy6W6x/quote.js?theme=0&f=12&display=0,0,0,1,0,0,0,1"></script><a target="_blank" title="51la网站统计" href="https://v6.51.la/land/JhwXbvPO5Ijy6W6x"><img src="https://sdk.51.la/icon/4-5.png"></a>
  _51la_lingque: <script src="https://sdk.51.la/perf/js-sdk-perf.min.js" crossorigin="anonymous"></script><script>new LingQue.Monitor().init({id:"JhwYVlJAdB7w0kYc"});</script>
  busuanzi: <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><span id="busuanzi_container_site_pv" ><a href="https://busuanzi.ibruce.info/" title="不蒜子">总访问量:<span id="busuanzi_value_site_pv"><i class="fa fa-spinner fa-spin"></i></span></a> <!--<span id="busuanzi_value_site_pv"><i class="fa fa-spinner fa-spin"></i></span>; SUV:<span id="busuanzi_value_site_uv"><i class="fa fa-spinner fa-spin"></i></span>; PPV:<span id="busuanzi_value_page_pv"><i class="fa fa-spinner fa-spin"></i></span>-->. </span>


favicon: favicon-fish.ico

wechat_subscriber:
  enabled: true
  qcode:
  description: 欢迎您扫一扫上面的微信公众号，订阅我的博客！

avatar:
  # in theme directory(source/images): /images/avatar.gif
  # in site  directory(source/uploads): /uploads/avatar.gif
  # You can also use other linking images.
  url: /images/avatar_sx_lite.png #author.jpg  #将我们的头像图片放置在blog/themes/next/source/images目录下，填写具体地址
  # If true, the avatar would be dispalyed in circle.
  rounded: true #鼠标放在头像上时是否旋转
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1 #头像放缩指数
  # If true, the avatar would be rotated with the cursor.
  rotated: true #头像是否设为圆形，否则为矩形



# Social Accounts
# http://www.fontawesome.com.cn/faicons/#web-application
# https://www.w3schools.cn/icons/fontawesome5_icons_brands.asp
# 按照字母排序
Social_Accounts:
  Azure:
    name: Azure
    href:
    class: fa fa-terminal fa-2x
  bilibili:
    name: 哔哩哔哩/bilibili
    href: https://space.bilibili.com/19354848
    class: fab fa-twitch fa-2x
  csdn:
    name: csdn
    href: https://blog.csdn.net/yaokingson
    class: fab fa-blogger fa-2x
  dingding:
    name: dingding/钉钉
    href:
    class: fa fa-comment fa-2x
  dockerhub:
    name: dockerhub
    href: https://hub.docker.com/u/lordyao
    class: fab fa-docker fa-2x
  douban:
    name: 豆瓣
    href:
    class: fa fa-imdb fa-2x
  facebook:
    name: facebook
    href:
    class: fab fa-facebook fa-2x
  gitee:
    name: gitee
    href: https://gitee.com/yaoqs
    class: fab fa-git fa-2x
  github_follow:
    href: https://ghbtns.com/github-btn.html?user=yaoqs&type=follow&count=true
    code: <iframe src="https://ghbtns.com/github-btn.html?user=yaoqs&amp;type=follow&amp;count=true" scrolling="no" width="150" height="20" frameborder="0"></iframe>
  github:
    name: github
    href: https://github.com/yaoqs
    class: fab fa-github fa-2x
  instagram:
    name: instagram
    href:
    class: fab fa-instagram fa-2x
  linkedin:
    name: linkin/领英
    href:
    class: fab fa-linkedin-in fa-2x
  pinterest:
    name: pinterest
    href:
    class: fab fa-pinterest-square fa-2x
  QQ:
    name: QQ
    href:
    class: fab fa-qq fa-2x
  reddit:
    name: reddit
    href:
    class: fab fa-reddit-alien fa-2x
  skype:
    name: skype
    href:
    class: fab fa-skype fa-2x
  slack:
    name: slack
    href:
    class: fab fa-slack fa-2x
  StackOverflow:
    name: StackOverflow
    href:
    class: fab fa-stack-overflow fa-2x
  telegram:
    name: telegram
    href:
    class: fab fa-telegram-plane fa-2x
  tumblr:
    name: tumblr
    href:
    class: fab fa-tumblr fa-2x
  twitter:
    name: twitter/推特
    href: http://twitter.com/Lord_Honor_Yao
    class: fab fa-twitter fa-2x
  wechat:
    name: wechat/微信
    href:
    class: fab fa-weixin fa-2x
  weibo:
    name: weibo/微博
    href: http://weibo.com/lordyao
    class: fab fa-weibo fa-2x
  weibostar:
    name: 加关注
    js: https://tjs.sjs.sinajs.cn/open/api/js/wb.js
    button: <wb:follow-button uid="1262655355" type="red_2" width="86" height="24"></wb:follow-button>
    href: https://widget.weibo.com/relationship/followbutton.php?btn=red&amp;style=2&amp;uid=1262655355&amp;width=86&amp;height=24&amp;language=zh_cn
    code: <iframe src="https://widget.weibo.com/relationship/followbutton.php?btn=red&amp;style=2&amp;uid=1262655355&amp;width=86&amp;height=24&amp;language=zh_cn" scrolling="no" marginheight="0" width="86" height="24" frameborder="0"></iframe>
  whatsapp:
    name: whatsapp
    href:
    class: fab fa-whatsapp fa-2x
  youtube:
    name: youtube
    href:
    class: fab fa-youtube-square fa-2x
  zhifubao:
    name:
    class: fab fa-alipay fa-2x
  zhihu:
    name: 知乎
    href:
    class: fab fa-zhihu fa-2x

Menu:
  Index:
    name: 首页/Index
    url: /
    icon: fas fa-home
  Tags:
    name: 标签/Tags
    url: /tags
    icon: fas fa-tags
  Categories:
    name: 归类/Categories
    url: /categories
    icon: fas fa-bookmark
  Archives:
    name: 文档/Archives
    url: /archives
    icon: fas fa-archive

Reward:
  enable: true
  comment: 大吉大利 今晚吃鸡
  wechatpay: /images/微信收款码.png
  wechatreward: /images/微信打赏码.png
  alipay: /images/支付宝收款码.jpg
  zhifubao_redpackage: /images/支付宝红包码.png
  paypal:
    name: paypal.me/LordYao
    href: https://www.paypal.com/cgi-bin/webscr?cmd=_xclick&business=243292490@qq.com&currency_code=USD&amount=1&return=http://yaoqs.github.com/about&item_name=LordYao%27s%20Blog&undefined_quantity=1
  #bitcoin: /images/bitcoin.jpg

#————————————————
#版权声明：本文为CSDN博主「nightmare_dimple」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
#原文链接：https://blog.csdn.net/nightmare_dimple/article/details/86661502

Journal:
  title: FUTURE & CIVILIZATION
  subtitle: Natural/Social Philosophy & Infomation Sciences
  Author: Yao Qing-sheng
  Author-cn: 要庆生
  Original: true

Copyright:
  since: 2019 #建站时间
  admin: LordYao #别填bool型，最后显示的东西是copyright || author，即左边没有设置的话就显示作者
  Statement: 版权声明：本文为「LordYao」的原创文章，遵循 CC 4.0 BY-NC-SA 版权协议，转载请附上原文出处链接及本声明。
  url: 原文链接：
  creative_commons:
    license: BY-NC-SA
    url:
    sidebar: true
    post: true
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.miitbeian.gov.cn
  beian:
    enable: false #是否显示网站备案信息
    icp:


theme: jekyll-theme-dinky

#========================theme-about plugins config======================
# hexo-tag-cloud
# https://github.com/D0n9X1n/hexo-tag-cloud
# https://www.goat1000.com/tagcanvas-options.php
tag_cloud:
    textFont: null
    textColor: null
    textHeight: 5
    outlineColor: '#E2E1D1'
    maxSpeed: 0.05 # range from [0.01 ~ 1]
    pauseOnSelected: false # true means pause the cloud tag movement when highlight a tag

# 高亮
# https://hexo.io/zh-cn/docs/syntax-highlight.html
highlight:
  enable: true
  auto_detect: false
  line_number: true
  line_threshold: 0
  tab_replace: ''
  exclude_languages:
    - example
  wrap: true
  hljs: false

# 文章字数统计插件
wordCount:
  enable: true # 将这个值设置为 true 即可.
  postWordCount: true
  min2read: true
  totalCount: true



# Canvas-nest
# Dependencies: https://github.com/theme-next/theme-next-canvas-nest
canvas_nest: # 网络背景
  enable: true
  onmobile: true # display on mobile or not
  color: '0,0,0' # RGB values, use ',' to separate
  opacity: 0.5 # the opacity of line: 0~1
  zIndex: -1 # z-index property of the background
  count: 150 # the number of lines

# JavaScript 3D library.
# Dependencies: https://github.com/theme-next/theme-next-three
# three_waves
three_waves: false
# canvas_lines
canvas_lines: false
# canvas_sphere
canvas_sphere: false

# Canvas-ribbon
# Dependencies: https://github.com/theme-next/theme-next-canvas-ribbon
# size: The width of the ribbon.
# alpha: The transparency of the ribbon.
# zIndex: The display level of the ribbon.
canvas_ribbon:
  enable: false
  size: 300
  alpha: 0.6
  zIndex: -1
