name: scholar-future
description: A scholar magazine/journal like blog
keywords: scholar-like blog
logo: /images/githubavatar.png
slogan: 解放思想，发展生产力
slogan2: 为天地立心<br>为生民立命<br>为往圣继绝学<br>为万世开太平<br> &emsp;&emsp;&emsp;&emsp;--张载
Email: 350788415@qq.com
Author: Yao Qing-sheng
githubname: yaoqs
Address: Department of Natural/Social Philosophy & Infomation Sciences, CHINA
Repositories_Pages: https://yaoqs.github.io/
rss: /atom.xml
disqus: 
custom_html_list: 
  About: about.html
  Lab: Lab.html
  Navigator: navigator.html
  Feature: feature.html
  Donate: donate.html
  Game: game.html
  music: music.html

404page: toolkit.html



site_visit_tongji:
  google_analytics:
  cnzz: <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" :"http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1278269244'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1278269244%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
  umengplus: <script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" :"http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1278269244'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s4.cnzz.com/z_stat.php%3Fid%3D1278269244%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
  qq_ta: <script type="text/javascript" src="https://tajs.qq.com/stats?sId=66496804" charset="UTF-8" async></script>
  bdtj: <script type="text/javascript">var _hmt = _hmt || [];(function() {  var hm = document.createElement("script");  hm.src = "https://hm.baidu.com/hm.js?2023f967cb85513ede1b6a3d58177776";  var s = document.getElementsByTagName("script")[0];   s.parentNode.insertBefore(hm, s);})();</script>
  flagcounter: <a href="https://info.flagcounter.com/tQfY"><img src="https://s11.flagcounter.com/mini/tQfY/bg_FFFFFF/txt_000000/border_CCCCCC/flags_0/" alt="Flag Counter" border="0"></a>
  _360fenxi: <script>(function(b,a,e,h,f,c,g,s){b[h]=b[h]||function(){(b[h].c=b[h].c||[]).push(arguments)};b[h].s=!!c;g=a.getElementsByTagName(e)[0];s=a.createElement(e);s.src="//s.union.360.cn/"+f+".js";s.defer=!0;s.async=!0;g.parentNode.insertBefore(s,g)})(window,document,"script","_qha",332983,false);</script>
  _51la: <script type="text/javascript" src="https://js.users.51.la/20526175.js" async></script>
  busuanzi: <script async src="//busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script><span id="busuanzi_container_site_pv">本站总访问量<span id="busuanzi_value_site_pv"></span>次</span>





favicon:
  small: /images/robot_lite.jpg


avatar:
  # in theme directory(source/images): /images/avatar.gif
  # in site  directory(source/uploads): /uploads/avatar.gif
  # You can also use other linking images.
  url: /images/avatar_sx_lite.png #author.jpg  #将我们的头像图片放置在blog/themes/next/source/images目录下，填写具体地址
  # If true, the avatar would be dispalyed in circle.
  rounded: true #鼠标放在头像上时是否旋转
  # The value of opacity should be choose from 0 to 1 to set the opacity of the avatar.
  opacity: 1 #头像放缩指数
  # If true, the avatar would be rotated with the cursor.
  rotated: true #头像是否设为圆形，否则为矩形

# 网站副标题，打字效果
# 如果有符号 ‘ ，请在 ’ 前面加上 \
subtitle: 
  enable: true
  loop: true # 是否循环
  showCursor: true # 是否显示光标
  startDelay: 300 # 开始延迟
  typeSpeed: 100 # 打字速度
  backSpeed: 50 # 删除速度
  sub1: 解放思想，发展生产力
  sub2: 为天地立心
  sub3: 为生民立命
  sub4: 为往圣继绝学
  sub5: 为万世开太平
  sub6: 知行合一
  sub7: 天之道，利而不害；圣人之道，为而不争

# 文章字数统计插件
wordCount:
  enable: true # 将这个值设置为 true 即可.
  postWordCount: true
  min2read: true
  totalCount: true

# Social Accounts
#  http://www.fontawesome.com.cn/faicons/#web-application
Social_Accounts:
  weibo: 
    name: weibo/微博
    href: http://weibo.com/lordyao
    class: fa fa-weibo fa-2x
  weibostar: <wb:follow-button uid="1262655355" type="red_1" width="63" height="24" ></wb:follow-button>
  bilibili: 
    name: 哔哩哔哩/bilibili
    href: https://space.bilibili.com/19354848
    class: fa fa-share fa-2x
  wechat: 
    name: wechat/微信
    href: 
    class: fa fa-weixin fa-2x
  QQ: 
    name: QQ
    href: 
    class: fa fa-qq fa-2x

  github: 
    name: github
    href: https://github.com/yaoqs
    class: fa fa-github-square fa-2x
  dockerhub: 
    name: dockerhub
    href: https://hub.docker.com/u/lordyao
    class: fa fa-github-square fa-2x
  gitee: 
    name: gitee
    href: https://gitee.com/yaoqs
    class: fa fa-github-square fa-2x
  csdn: 
    name: csdn
    href: https://blog.csdn.net/yaokingson
    class: fa fa-share fa-2x
  StackOverflow: 
    name: StackOverflow
    href: 
    class: fa fa-stack-overflow fa-2x
  Azure: 
    name: Azure
    href: 
    class: fa fa-terminal fa-2x
  dingding: 
    name: dingding/钉钉
    href: 
    class: fa fa-comment fa-2x
  instagram:
    name: instagram
    href: 
    class: fa fa-instagram fa-2x
  pinterest:
    name: pinterest
    href: 
    class: fa fa-pinterest-square fa-2x
  facebook:
    name: facebook
    href: 
    class: fa fa-facebook-square fa-2x
  twitter: 
    name: twitter/推特
    href: http://twitter.com/Lord_Honor_Yao
    class: fa fa-twitter-square fa-2x
  linkedin: 
    name: linkin/领英
    href: 
    class: fa fa-linkedin-square fa-2x
  douban: 
    name: 豆瓣
    href: 
    class: fa fa-imdb fa-2x
  telegram:
    name: telegram
    href: 
    class: fa fa-telegram fa-2x
  youtube:
    name: yooutube
    href:
    class: fa fa-youtube fa-2x
  whatsapp:
    name: whatsapp
    href:
    class: fa fa-whatsapp fa-2x
  tumblr:
    name: tumblr
    href:
    class: fa fa-tumblr fa-2x
  slack:
    name: slack
    href:
    class: fa fa-slack fa-2x
  skype:
    name: skype
    href:
    class: fa fa-skype fa-2x
  reddit:
    name: reddit
    href:
    class: fa fa-reddit fa-2x


# Canvas-nest
# Dependencies: https://github.com/theme-next/theme-next-canvas-nest
canvas_nest: # 网络背景
  enable: true
  onmobile: true # display on mobile or not
  color: '0,0,0' # RGB values, use ',' to separate
  opacity: 0.5 # the opacity of line: 0~1
  zIndex: -1 # z-index property of the background
  count: 150 # the number of lines

# JavaScript 3D library.
# Dependencies: https://github.com/theme-next/theme-next-three
# three_waves
three_waves: false
# canvas_lines
canvas_lines: false
# canvas_sphere
canvas_sphere: false

# Canvas-ribbon
# Dependencies: https://github.com/theme-next/theme-next-canvas-ribbon
# size: The width of the ribbon.
# alpha: The transparency of the ribbon.
# zIndex: The display level of the ribbon.
canvas_ribbon:
  enable: false
  size: 300
  alpha: 0.6
  zIndex: -1

menu:
  Index:
    url: /
    icon: fas fa-home
  Tags:
    url: /tags
    icon: fas fa-tags
  Categories:
    url: /categories
    icon: fas fa-bookmark
  Archives:
    url: /archives
    icon: fas fa-archive
  About:
    url: /about
    icon: fas fa-user-circle-o
  Friends:
    url: /friends
    icon: fas fa-address-book
  Medias:
    icon: fas fa-list
    children:
      - name: Musics
        url: /musics
        icon: fas fa-music
      - name: Movies
        url: /movies
        icon: fas fa-film
      - name: Books
        url: /books
        icon: fas fa-book
      - name: Galleries
        url: /galleries
        icon: fas fa-image
 
reward:
  enable: true
  comment: 大吉大利 今晚吃鸡
  wechatpay: /images/微信收款码.png
  wechatreward: images/微信打赏码.png
  alipay: /images/支付宝收款码.jpg
  zhifubao_redpackage: /images/支付宝红包码.png
  paypal: paypal.me/LordYao
  #bitcoin: /images/bitcoin.jpg

#————————————————
#版权声明：本文为CSDN博主「nightmare_dimple」的原创文章，遵循 CC 4.0 BY-SA 版权协议，转载请附上原文出处链接及本声明。
#原文链接：https://blog.csdn.net/nightmare_dimple/article/details/86661502

journal:
  title: FUTURE & CIVILIZATION
  subtitle: Natural/Social Philosophy & Infomation Sciences
  Author: Yao Qing-sheng
  Author-cn: 要庆生
  Original: true

copyright: 
  since: 2019 #建站时间
  admin: LordYao #别填bool型，最后显示的东西是copyright || author，即左边没有设置的话就显示作者
  Statement: 版权声明：本文为「LordYao」的原创文章，遵循 CC 4.0 BY-NC-SA 版权协议，转载请附上原文出处链接及本声明。
  url: 原文链接：
  creative_commons:
    license: BY-NC-SA
    url: 
    sidebar: true
    post: true
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # http://www.miitbeian.gov.cn
  beian:
    enable: false #是否显示网站备案信息
    icp:


theme: jekyll-theme-dinky